[package]
name = "keyed-stream-map"
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
description = "Keyed StreamMap with expected O(1) lookup and removal."
repository = "https://github.com/abhishekshree/keyed-stream-map"
documentation = "https://docs.rs/keyed-stream-map"
keywords = ["stream", "async", "tokio", "map", "merge"]
categories = ["asynchronous", "data-structures"]
readme = "README.md"
exclude = ["/.github/**", "/CONTRIBUTING.md", "/Cargo.lock"]

[dependencies]
futures-core = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-test = "0.4"
futures = "0.3"

[profile.release]
opt-level = 3
lto = "thin"
